### ISSUE TITLE
大大你好，请教你一个问题哈

### ISSUE THREAD

**Issue by neo1201** [finddreams/AndModulePractice#1]
最近刚刚接触多模块的开发，有这样一个业务场景，就是登陆用户的信息，需要多个模块共享，请问你是怎么处理的呢？
还有网络接口是 统一放在基础模块，还是放在不同模块中？

1. 如果，网络接口都按模块，放在不同模块，登陆获取到的用户基本信息UserModel 这个实体类，是放在登陆模块，我在其它模块获取UserModel 貌似就获取不到了，这个时候，我在基础库中写一个 LoginUserManager，来管理用户信息，然后，其它模块通过基础库中LoginUserManager 获取UserModel ，这个时候，需要把UserModel 放到基础库中，感觉非常割裂

2. 还有一种方案，就是把所有的网络接口都放在基础库中，然后，各个模块做网络请求的时候，从基础库中调用基础库中提供的接口，我是偏向这种方案，但是，同事都说，网络接口要放到相应的模块中。也就是第一种方案。

请教一下大大，这个时候，该怎么处理这个UserModel的信息共享呢

**Comment by finddreams** [comment]
我是觉得网络接口是应该放在不同的模块里面，由不同模块的负责人维护，通用的UserModel实体类则可以放到base基础模块里，当然其实也可以放到用户模块里，通过跨模块的服务调用获取到信息。
