### ISSUE TITLE
 请问组件化中怎么使用butterknife ,你的项目中没有体现这一点

### ISSUE THREAD

**Issue by OOMROO** [finddreams/AndModulePractice#2]
你的module_base 中用到了 butterknife 但module_home,和module_user 两个组件中都是用的findViewByid 你把@BindView的代码注释掉了。请问下在组件化开发中butterknife怎么使用的？

**Comment by finddreams** [comment]
https://github.com/JakeWharton/butterknife  github主页上有说明
